### ISSUE TITLE
[Feature] Camera Monitoring Report Entry

### ISSUE THREAD

**Issue by crobinson42** [crobinson42/therms-public#12]
Wireframe Sketch:
https://www.dropbox.com/s/ohtaucra86af8cf/Screenshot%202016-03-24%2021.18.04.png?dl=0

@jackschappell & @billpreston Needs critique and input...

**Comment by billpreston** [comment]
I like it!   Simple, to the point, easy to navigate through and read.

**Comment by crobinson42** [comment]
@billpreston are there any specific inputs you'd like to see?

**Comment by billpreston** [comment]
Need a block for the specific property name/address you are no trespassing the individual from.    

 

Also, I realize that we have to make them generic for companies in other states but I’m pretty sure if we issue a no trespass to someone here in the Communist State of California, we have to actually cite the city/county/state code on the violation.

**Comment by crobinson42** [comment]
@billpreston Check out the moqup wireframe - I added a penal code reference.

**Comment by billpreston** [comment]
Nice!!!!  That will make community managers very happy!  As far as I know, nobody else provides that kind of detailed reporting for these types of incidents.  That will definitely set THERMS apart.

**Comment by jackschappell** [comment]
I think some of the comment sections got mixed up, but the camera monitoring idea looks great! If it is for a specific time, (for cameras that are busy on activity), I would recommend making sure the output in the report doesn't take up a massive amount of space for that entry, since a busy night might result in a very long page. Other than that, I think this would work very well. It also seems to be very stupid-proof, which will help with those who are new to the system!
