### ISSUE TITLE
[Feature] Trespass Violation

### ISSUE THREAD

**Issue by crobinson42** [crobinson42/therms-public#14]
** Not referring to it as `602` since not all states have the same penal code reference.

Wireframe sketch:
https://www.dropbox.com/s/5clx2svf7i6a8b6/Screenshot%202016-03-24%2022.02.45.png?dl=0

@jackschappell @billpreston needs collaboration input and critiq..

**Comment by jackschappell** [comment]
I would recommend adding the XREF section since some locations may still require it, however that looks awesome!

As I think someone else mentioned, for the legality of it, if you are allowing the output of an actual form, you'll also want the ability to add specific text based upon local No Trespass Form requirements to make it valid in said locations. If this is just to simply log the fact that a No Trespass Form was issued, then it shouldn't be an issue so long as an image or screenshot of the actual No Trespass Form gets uploaded with the record, (which it appears you covered here with an upload option).

**Comment by crobinson42** [comment]
@jackschappell This feature is in SBX, please test and close.

**Comment by jackschappell** [comment]
All tested and working!
