### ISSUE TITLE
Report status change to complete requires at least 1 report entry

### ISSUE THREAD

**Issue by crobinson42** [crobinson42/therms-public#40]
Do not allow a Report status to change to `completed` if there are no report entries.

@jackschappell Do you think a feature idea to allow a report to be completed/approved without a Location selected is a good idea? ie:
> A non-standard company event takes place and there is no real need to create a location for a 4-hr shift but the supervisor asks the guard to complete a report for the shift & date (no location exists).

**Comment by jackschappell** [comment]
I would say yes, but only if the user can write-in a location. That way it can still be searched for properly. I would also recommend making it so that any written-in locations show the user a suggestion of existing property names as they type, including previously written-in locations, so they can stay grouped together properly if more than one report exists for that written-in location. (I think your existing design already takes care of some of this).

**Comment by crobinson42** [comment]
This feature was added.
