### ISSUE TITLE
Report dates cannot be changed

### ISSUE THREAD

**Issue by jackschappell** [crobinson42/therms-public#41]
The creation date on a report, regardless of access rights, cannot be changed to reflect the report's shift date if started on a different date. This can be problematic, especially if a report is created after midnight during an overnight shift, or if a report is somehow lost from a previous date and needs to be rewritten at a later time.

**Comment by crobinson42** [comment]
This is expected behavior. The backend performs a task on a Report every time a report entry is saved/updated/destroy `reconcileReportInformationWithReportEntryRelations(reportId)` which searches the DB for Report Entry’s that belong to the report and updates the date of the Report to be the EARLIEST dated Report Entry… and also updates authors & activity type information from report information.

Do you suggest a manual adjustment of the report date?

**Comment by jackschappell** [comment]
Pretty much, similar to how the old version allowed it.

**Comment by jackschappell** [comment]
An example of my reasoning behind this would be for the overnight Dispatch reports. If a Dispatcher starts at midnight, but the reports are for an overnight shift from the previous date, it gets confusing quickly for the client when they try to sort through incidents for that shift date, rather than the actual date of when the entries were created.

The existing system is perfectly fine if there is a backup method for overriding the report date and manually setting them for situations like this.

**Comment by crobinson42** [comment]
this has been added to sbx and only capable during a report that is 'in-progress'

**Comment by jackschappell** [comment]
This appears to be working on the Sandbox. You can push it to production.
